Add undefined check for event.key and some additional unit tests
PebblePad/keysy-peasy pull request #13
Opened 2020-08-26 15:41 UTC by cdashrowe

This PR adds an undefined check around the event.key in handler within Shortcuts.ts as some events seemingly slip through without a key being present.

Also added additional unit tests to ensure the callback is fired in the correct circumstances.

2020-08-27 06:33 UTC, Exigerr commented on src/tests/Shortcuts.spec.ts
> +        describe("and a shortcut is registered for the events key", () => {
**NIT:** `event's`.
Same on line 98

2020-08-27 06:33 UTC, Exigerr commented
Doesn't have to be part of this but CHANGELOG will also need updating before release :)

2020-08-27 06:35 UTC, Exigerr approved these changes, later dismissed
Minor wording nitpick, but otherwise looks good 👍

2020-08-27 09:03 UTC, tony1377 approved these changes, later dismissed

2020-08-28 08:20 UTC, Exigerr requested changes

2020-08-28 08:20 UTC, Exigerr commented on src/tests/Shortcuts.spec.ts
> +            test("it should trigger the callback", () => {
This should be `it should not trigger the callback` :)

2020-08-28 08:30 UTC, Exigerr approved these changes

2020-09-04 09:01 UTC, tony1377 approved these changes

2020-09-04 11:50 UTC, merged